name: Bektash van Bruinessen
favicon: null
layout_spectrum: 0.04696862772107124
typography_spectrum: 0.39351
title: 'Pianist, Teacher & Co-Founder of Combined Creatives'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#131313'
    - '#bbbbbb'
    - '#4a4a4a'
    - '#868686'
    - '#e1e1e1'
  brandStrength: 0.38633119803853333
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
